CREATE TABLE IF NOT EXISTS phq9_answers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  result_id INT NOT NULL,
  question_number TINYINT UNSIGNED NOT NULL CHECK (question_number BETWEEN 1 AND 9),
  score TINYINT UNSIGNED NOT NULL CHECK (score BETWEEN 0 AND 3),
  FOREIGN KEY (result_id) REFERENCES phq9_results(id) ON DELETE CASCADE
);
